name: Exemplo de fluxo de trabalho

on:
  workflow_dispatch:

jobs:
  acao_inicial_job:
    runs-on: ubuntu-latest
    steps:
      -name: Imprime Olá
        run: echo "Olá"
      -name: Imprime Tchau
        run: echo "Tchau"
